# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            apuntes de POO
tagline:          'apuntes de POO'
description:      '.'
url:              http://git.juangonzalez.com.es

author:
  name:           'Juan González'
  url:            https://twitter.com/JuanGnzalez

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jmanuelgg/jmanuelgg.github.io
